project_id = "mqajiohlswemeukguahm"

[functions.notify-business]
verify_jwt = false

[functions.notify-client]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.ivr-api]
verify_jwt = false
